<?php
require __DIR__ . '/../../includes/bootstrap.php'; require_role(['admin']);
if ($_SERVER['REQUEST_METHOD']==='POST') {
 verify_csrf(); $a=$_POST['action']??'';
 try {
  if($a==='turma'){ $q=db()->prepare('INSERT INTO scp_turmas(nome,turno) VALUES(?,?)');$q->execute([trim($_POST['nome']),$_POST['turno']]);audit('criar_turma','scp_turmas',(int)db()->lastInsertId()); }
  elseif($a==='aluno'){ $cpf=preg_replace('/\D/','',$_POST['cpf']);$q=db()->prepare('INSERT INTO scp_alunos(nome,cpf,data_nascimento,turma_id,foto,qr_token) VALUES(?,?,?,?,?,?)');$q->execute([trim($_POST['nome']),$cpf?:null,$_POST['data_nascimento']?:null,$_POST['turma_id']?:null,filter_var($_POST['foto'],FILTER_VALIDATE_URL)?$_POST['foto']:null,bin2hex(random_bytes(32))]);$novoId=(int)db()->lastInsertId();audit('criar_aluno','scp_alunos',$novoId);redirect('admin/cracha.php?id='.$novoId.'&emit=1'); }
  elseif($a==='responsavel'){ $q=db()->prepare('INSERT INTO scp_responsaveis(nome,cpf,email,telefone,senha_hash) VALUES(?,?,?,?,?)');$q->execute([trim($_POST['nome']),preg_replace('/\D/','',$_POST['cpf']),strtolower(trim($_POST['email'])),trim($_POST['telefone']),password_hash($_POST['senha'],PASSWORD_DEFAULT)]);audit('criar_responsavel','scp_responsaveis',(int)db()->lastInsertId()); }
  elseif($a==='vinculo'){ $q=db()->prepare('INSERT INTO scp_aluno_responsavel(aluno_id,responsavel_id,parentesco,autoriza_consulta,autoriza_retirada) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE parentesco=VALUES(parentesco),autoriza_consulta=VALUES(autoriza_consulta),autoriza_retirada=VALUES(autoriza_retirada)');$q->execute([(int)$_POST['aluno_id'],(int)$_POST['responsavel_id'],trim($_POST['parentesco']),isset($_POST['consulta']),isset($_POST['retirada'])]);audit('vincular_responsavel','scp_alunos',(int)$_POST['aluno_id']); }
  elseif($a==='usuario'){ $q=db()->prepare('INSERT INTO scp_usuarios(nome,email,senha_hash,perfil) VALUES(?,?,?,?)');$q->execute([trim($_POST['nome']),strtolower(trim($_POST['email'])),password_hash($_POST['senha'],PASSWORD_DEFAULT),$_POST['perfil']]);audit('criar_usuario','scp_usuarios',(int)db()->lastInsertId()); }
  elseif($a==='toggle'){ $table=in_array($_POST['table'],['scp_alunos','scp_responsaveis','scp_turmas','scp_usuarios'],true)?$_POST['table']:'';if(!$table)throw new Exception('Inválido');$q=db()->prepare("UPDATE $table SET ativo=1-ativo WHERE id=?");$q->execute([(int)$_POST['id']]);audit('alterar_status',$table,(int)$_POST['id']); }
  flash('Operação realizada.');
 } catch(Throwable $e){ flash('Não foi possível salvar: '.$e->getMessage(),'danger'); } redirect('admin/index.php');
}
$scp_turmas=db()->query('SELECT * FROM scp_turmas ORDER BY nome')->fetchAll();$scp_alunos=db()->query('SELECT a.*,t.nome turma FROM scp_alunos a LEFT JOIN scp_turmas t ON t.id=a.turma_id ORDER BY a.nome')->fetchAll();$resp=db()->query('SELECT * FROM scp_responsaveis ORDER BY nome')->fetchAll();$users=db()->query('SELECT * FROM scp_usuarios ORDER BY nome')->fetchAll();
layout_header('Painel da escola');
?>
<div class="page-heading"><div><span class="gate-eyebrow">PAINEL</span><h1>Painel da escola</h1><p>Cadastros e controle escolar</p></div><div class="page-actions"><a class="btn btn-success" href="<?=url('portaria/convites.php')?>">Convidar responsável</a><a class="btn btn-outline-primary" href="relatorios.php">Relatórios</a><a class="btn btn-primary" href="<?=url('portaria/index.php')?>">Abrir portaria</a></div></div>
<ul class="nav nav-pills scp-tabs gap-2 mb-4 flex-nowrap overflow-auto" role="tablist"><?php foreach(['scp_alunos'=>'Alunos','scp_responsaveis'=>'Responsáveis','scp_turmas'=>'Turmas','vinculos'=>'Vínculos','scp_usuarios'=>'Usuários'] as $id=>$label):?><li><button class="nav-link <?=$id==='scp_alunos'?'active':''?>" data-bs-toggle="tab" data-bs-target="#<?=$id?>"><?=$label?></button></li><?php endforeach?></ul>
<div class="tab-content">
<section class="tab-pane fade show active" id="scp_alunos"><div class="section-card"><h2>Novo aluno</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="aluno"><div class="col-md-4"><input class="form-control" name="nome" placeholder="Nome completo" required></div><div class="col-md-2"><input class="form-control" name="cpf" placeholder="CPF"></div><div class="col-md-2"><input type="date" class="form-control" name="data_nascimento"></div><div class="col-md-2"><select class="form-select" name="turma_id"><option value="">Turma</option><?php foreach($scp_turmas as $t):?><option value="<?=$t['id']?>"><?=e($t['nome'])?></option><?php endforeach?></select></div><div class="col-md-2"><input class="form-control" name="foto" placeholder="URL da foto"></div><div><button class="btn btn-primary">Cadastrar</button></div></form></div>
<?php if($scp_alunos):?><div class="data-table-card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Aluno</th><th>Turma</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($scp_alunos as $a):?><tr><td><?=e($a['nome'])?></td><td><?=e($a['turma']??'-')?></td><td><span class="status-pill <?=$a['ativo']?'active':'inactive'?>"><?=$a['ativo']?'Ativo':'Inativo'?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="cracha.php?id=<?=$a['id']?>&emit=1">Crachá</a> <?=toggle_form('scp_alunos',$a)?></td></tr><?php endforeach?></tbody></table></div></div><?php else:?><div class="empty-state">Nenhum aluno cadastrado ainda.</div><?php endif?></section>
<section class="tab-pane fade" id="scp_responsaveis"><?=simple_form('responsavel',['nome'=>'Nome','cpf'=>'CPF','email'=>'E-mail','telefone'=>'Telefone','senha'=>'Senha inicial'],'Cadastrar responsável')?><?php if($resp):?><div class="data-table-card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Responsável</th><th>CPF</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($resp as $r):?><tr><td><?=e($r['nome'])?></td><td><?=e($r['cpf'])?></td><td><span class="status-pill <?=$r['ativo']?'active':'inactive'?>"><?=$r['ativo']?'Ativo':'Inativo'?></span></td><td class="text-end"><?=toggle_form('scp_responsaveis',$r)?></td></tr><?php endforeach?></tbody></table></div></div><?php else:?><div class="empty-state">Nenhum responsável cadastrado ainda.</div><?php endif?></section>
<section class="tab-pane fade" id="scp_turmas"><div class="section-card"><h2>Nova turma</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="turma"><div class="col"><input class="form-control" name="nome" placeholder="Nome da turma" required></div><div class="col"><select class="form-select" name="turno"><option value="manha">Manhã</option><option value="tarde">Tarde</option><option value="integral">Integral</option><option value="noite">Noite</option></select></div><div class="col-auto"><button class="btn btn-primary">Cadastrar</button></div></form></div></section>
<section class="tab-pane fade" id="vinculos"><div class="section-card"><h2>Vincular responsável a aluno</h2><form method="post" class="row g-3"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="vinculo"><div class="col-md"><select class="form-select" name="aluno_id" required><option value="">Aluno</option><?php foreach($scp_alunos as $a):?><option value="<?=$a['id']?>"><?=e($a['nome'])?></option><?php endforeach?></select></div><div class="col-md"><select class="form-select" name="responsavel_id" required><option value="">Responsável</option><?php foreach($resp as $r):?><option value="<?=$r['id']?>"><?=e($r['nome'])?></option><?php endforeach?></select></div><div class="col-md"><input class="form-control" name="parentesco" placeholder="Parentesco" required></div><div class="col-12"><label class="me-3"><input type="checkbox" name="consulta" checked> Consulta</label><label><input type="checkbox" name="retirada"> Retirada</label></div><div><button class="btn btn-primary">Vincular</button></div></form></div></section>
<section class="tab-pane fade" id="scp_usuarios"><?=simple_form('usuario',['nome'=>'Nome','email'=>'E-mail','senha'=>'Senha'],'Cadastrar usuário','<select class="form-select" name="perfil"><option value="portaria">Portaria</option><option value="admin">Administrador</option></select>')?></section>
</div><?php layout_footer();
function toggle_form(string $table,array $row):string{return '<form method="post" class="d-inline"><input type="hidden" name="csrf" value="'.e(csrf()).'"><input type="hidden" name="action" value="toggle"><input type="hidden" name="table" value="'.e($table).'"><input type="hidden" name="id" value="'.(int)$row['id'].'"><button class="btn btn-sm btn-outline-'.($row['ativo']?'danger':'success').'">'.($row['ativo']?'Inativar':'Ativar').'</button></form>';}
function simple_form(string $action,array $fields,string $button,string $extra=''):string{$s='<div class="section-card"><h2>'.e($button).'</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="'.e(csrf()).'"><input type="hidden" name="action" value="'.e($action).'">';foreach($fields as $n=>$p)$s.='<div class="col-md"><input class="form-control" '.($n==='senha'?'type="password" minlength="8" ':'').'name="'.e($n).'" placeholder="'.e($p).'" required></div>';$s.=$extra.'<div class="col-auto"><button class="btn btn-primary">'.e($button).'</button></div></form></div>';return $s;}
