<?php
require __DIR__ . '/../../includes/bootstrap.php'; require_permission('student.manage');
$schoolService = \App\Support\ServiceFactory::schoolAdmin();
if ($_SERVER['REQUEST_METHOD']==='POST') {
 verify_csrf();
 try {
  $schoolService->handleAction($_POST, (string)($_SESSION['role'] ?? ''));
  flash('Operação realizada.');
 } catch(Throwable $e){ flash('Não foi possível salvar: '.$e->getMessage(),'danger'); } redirect('admin/index.php');
}
extract($schoolService->dashboardData(), EXTR_SKIP);
layout_header('Painel da escola');
?>
<div class="page-heading"><div><span class="gate-eyebrow">PAINEL</span><h1>Painel da escola</h1><p>Cadastros e controle escolar</p></div><div class="page-actions"><a class="btn btn-success" href="<?=url('portaria/convites.php')?>">Convidar responsável</a><a class="btn btn-outline-primary" href="relatorios.php">Relatórios</a><a class="btn btn-primary" href="<?=url('portaria/index.php')?>">Abrir portaria</a></div></div>
<ul class="nav nav-pills scp-tabs gap-2 mb-4 flex-nowrap overflow-auto" role="tablist"><?php $tabs=['scp_alunos'=>'Alunos','scp_responsaveis'=>'Responsáveis','scp_turmas'=>'Turmas','vinculos'=>'Vínculos']; if(($_SESSION['role']??'')==='admin'){$tabs['professores']='Professores';$tabs['scp_usuarios']='Usuários';$tabs['tema']='Tema';} foreach($tabs as $id=>$label):?><li><button class="nav-link <?=$id==='scp_alunos'?'active':''?>" data-bs-toggle="tab" data-bs-target="#<?=$id?>"><?=$label?></button></li><?php endforeach?></ul>
<div class="tab-content">
<section class="tab-pane fade show active" id="scp_alunos"><div class="section-card"><h2>Novo aluno</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="aluno"><div class="col-md-4"><input class="form-control" name="nome" placeholder="Nome completo" required></div><div class="col-md-2"><input class="form-control" name="cpf" placeholder="CPF"></div><div class="col-md-2"><input type="date" class="form-control" name="data_nascimento"></div><div class="col-md-2"><select class="form-select" name="turma_id"><option value="">Turma</option><?php foreach($scp_turmas as $t):?><option value="<?=$t['id']?>"><?=e($t['nome'])?></option><?php endforeach?></select></div><div class="col-md-2"><input class="form-control" name="foto" placeholder="URL da foto"></div><div><button class="btn btn-primary">Cadastrar</button></div></form></div>
<?php if($scp_alunos):?><div class="data-table-card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Aluno</th><th>Turma</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($scp_alunos as $a):?><tr><td><?=e($a['nome'])?></td><td><?=e($a['turma']??'-')?></td><td><span class="status-pill <?=$a['ativo']?'active':'inactive'?>"><?=$a['ativo']?'Ativo':'Inativo'?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="seguranca.php?id=<?=$a['id']?>">QR de segurança</a> <?=toggle_form('scp_alunos',$a)?></td></tr><?php endforeach?></tbody></table></div></div><?php else:?><div class="empty-state">Nenhum aluno cadastrado ainda.</div><?php endif?></section>
<section class="tab-pane fade" id="scp_responsaveis"><?=simple_form('responsavel',['nome'=>'Nome','cpf'=>'CPF','email'=>'E-mail','telefone'=>'Telefone','senha'=>'Senha inicial'],'Cadastrar responsável')?><?php if($resp):?><div class="data-table-card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Responsável</th><th>CPF</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($resp as $r):?><tr><td><?=e($r['nome'])?></td><td><?=e($r['cpf'])?></td><td><span class="status-pill <?=$r['ativo']?'active':'inactive'?>"><?=$r['ativo']?'Ativo':'Inativo'?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="cracha.php?responsavel_id=<?=$r['id']?>&emit=1">Crachá</a> <?=toggle_form('scp_responsaveis',$r)?></td></tr><?php endforeach?></tbody></table></div></div><?php else:?><div class="empty-state">Nenhum responsável cadastrado ainda.</div><?php endif?></section>
<section class="tab-pane fade" id="scp_turmas"><div class="section-card"><h2>Nova turma</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="turma"><div class="col"><input class="form-control" name="nome" placeholder="Nome da turma" required></div><div class="col"><select class="form-select" name="turno"><option value="manha">Manhã</option><option value="tarde">Tarde</option><option value="integral">Integral</option><option value="noite">Noite</option></select></div><div class="col-auto"><button class="btn btn-primary">Cadastrar</button></div></form></div></section>
<section class="tab-pane fade" id="vinculos"><div class="section-card"><h2>Vincular responsável a aluno</h2><form method="post" class="row g-3"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="vinculo"><div class="col-md"><select class="form-select" name="aluno_id" required><option value="">Aluno</option><?php foreach($scp_alunos as $a):?><option value="<?=$a['id']?>"><?=e($a['nome'])?></option><?php endforeach?></select></div><div class="col-md"><select class="form-select" name="responsavel_id" required><option value="">Responsável</option><?php foreach($resp as $r):?><option value="<?=$r['id']?>"><?=e($r['nome'])?></option><?php endforeach?></select></div><div class="col-md"><input class="form-control" name="parentesco" placeholder="Parentesco" required></div><div class="col-12"><label class="me-3"><input type="checkbox" name="consulta" checked> Consulta</label><label><input type="checkbox" name="retirada"> Retirada</label></div><div><button class="btn btn-primary">Vincular</button></div></form></div></section>
<?php if(($_SESSION['role']??'')==='admin'):?>
<section class="tab-pane fade" id="professores"><div class="section-card"><h2>Novo professor</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="professor"><div class="col-md"><input class="form-control" name="nome" placeholder="Nome" required></div><div class="col-md"><input class="form-control" name="email" placeholder="E-mail"></div><div class="col-md"><input class="form-control" name="telefone" placeholder="Telefone"></div><div class="col-md"><select class="form-select" name="usuario_id"><option value="">Sem usuário</option><?php foreach($users as $u):?><option value="<?=$u['id']?>"><?=e($u['nome'])?> - <?=e($u['perfil'])?></option><?php endforeach?></select></div><div class="col-auto"><button class="btn btn-primary">Cadastrar</button></div></form></div><div class="section-card"><h2>Vincular professor à turma</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="professor_turma"><div class="col-md"><select class="form-select" name="professor_id" required><option value="">Professor</option><?php foreach($professores as $p):?><option value="<?=$p['id']?>"><?=e($p['nome'])?></option><?php endforeach?></select></div><div class="col-md"><select class="form-select" name="turma_id" required><option value="">Turma</option><?php foreach($scp_turmas as $t):?><option value="<?=$t['id']?>"><?=e($t['nome'])?></option><?php endforeach?></select></div><div class="col-auto"><button class="btn btn-primary">Vincular</button></div></form></div><?php if($professores):?><div class="data-table-card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Professor</th><th>E-mail</th><th>Turmas</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($professores as $p):?><tr><td><?=e($p['nome'])?></td><td><?=e($p['email'] ?: $p['usuario_email'] ?: '-')?></td><td><?=e($profTurmas[$p['id']] ?? '-')?></td><td><span class="status-pill <?=$p['ativo']?'active':'inactive'?>"><?=$p['ativo']?'Ativo':'Inativo'?></span></td><td class="text-end"><?=toggle_form('scp_professores',$p)?></td></tr><?php endforeach?></tbody></table></div></div><?php endif?></section>
<section class="tab-pane fade" id="scp_usuarios"><?=simple_form('usuario',['nome'=>'Nome','email'=>'E-mail','senha'=>'Senha'],'Cadastrar usuário','<select class="form-select" name="perfil"><option value="portaria">Portaria</option><option value="secretaria">Secretaria</option><option value="professor">Professor</option><option value="admin">Administrador</option></select>')?></section>
<section class="tab-pane fade" id="tema">
  <div class="section-card">
    <h2>Tema do sistema</h2>
    <p class="text-muted">O tema escolhido pelo admin vale para todos os usuários.</p>
    <form method="post" class="theme-picker-grid">
      <input type="hidden" name="csrf" value="<?=e(csrf())?>">
      <input type="hidden" name="action" value="tema">
      <?php $currentTheme = $settings['tema'] ?? app_theme(); foreach(['classico'=>'Colorido atual','azul_branco'=>'Azul e branco moderno','preto_branco'=>'Preto e branco moderno'] as $value=>$label): ?>
        <label class="theme-choice theme-choice-<?=e($value)?> <?=$currentTheme===$value?'selected':''?>">
          <input type="radio" name="tema" value="<?=e($value)?>" <?=$currentTheme===$value?'checked':''?>>
          <span class="theme-swatch"><i></i><i></i><i></i></span>
          <strong><?=e($label)?></strong>
        </label>
      <?php endforeach ?>
      <button class="btn btn-primary btn-lg" type="submit">Salvar tema</button>
    </form>
  </div>
</section>
<?php endif?>
</div><?php layout_footer();
function toggle_form(string $table,array $row):string{return '<form method="post" class="d-inline"><input type="hidden" name="csrf" value="'.e(csrf()).'"><input type="hidden" name="action" value="toggle"><input type="hidden" name="table" value="'.e($table).'"><input type="hidden" name="id" value="'.(int)$row['id'].'"><button class="btn btn-sm btn-outline-'.($row['ativo']?'danger':'success').'">'.($row['ativo']?'Inativar':'Ativar').'</button></form>';}
function simple_form(string $action,array $fields,string $button,string $extra=''):string{$s='<div class="section-card"><h2>'.e($button).'</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="'.e(csrf()).'"><input type="hidden" name="action" value="'.e($action).'">';foreach($fields as $n=>$p)$s.='<div class="col-md"><input class="form-control" '.($n==='senha'?'type="password" minlength="8" ':'').'name="'.e($n).'" placeholder="'.e($p).'" required></div>';$s.=$extra.'<div class="col-auto"><button class="btn btn-primary">'.e($button).'</button></div></form></div>';return $s;}
